//! Integration tests for `libra-governor quota explain --replay`
//! (HORO-1767). Fixtures under `tests/fixtures/quota/` are generated by
//! `crates/cli/src/quota_cmd/fixtures_gen.rs` (`cargo test -p
//! libra-governor-cli --bin libra-governor generate -- --ignored` to
//! regenerate) — never hand-written JSON, since several wire fields use
//! the `time` crate's default (non-RFC3339) serde format.

use std::path::Path;
use std::process::Command;

use sha2::{Digest, Sha256};

fn bin() -> &'static str {
    env!("CARGO_BIN_EXE_libra-governor")
}

fn fixture(name: &str) -> String {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("tests/fixtures/quota")
        .join(name)
        .to_string_lossy()
        .into_owned()
}

fn run_raw(args: &[&str]) -> (bool, String, String) {
    let output = Command::new(bin())
        .args(args)
        .output()
        .unwrap_or_else(|e| panic!("failed to spawn libra-governor {args:?}: {e}"));
    (
        output.status.success(),
        String::from_utf8_lossy(&output.stdout).into_owned(),
        String::from_utf8_lossy(&output.stderr).into_owned(),
    )
}

fn run_json(fixture_name: &str, as_of: &str) -> serde_json::Value {
    let path = fixture(fixture_name);
    let (ok, stdout, stderr) = run_raw(&[
        "quota", "explain", "--replay", &path, "--as-of", as_of, "--json",
    ]);
    assert!(ok, "quota explain failed: {stderr}");
    serde_json::from_str(&stdout).unwrap_or_else(|e| panic!("invalid JSON output: {e}\n{stdout}"))
}

fn run_text(fixture_name: &str, as_of: &str, width: &str) -> String {
    let path = fixture(fixture_name);
    let (ok, stdout, stderr) = run_raw(&[
        "quota", "explain", "--replay", &path, "--as-of", as_of, "--width", width,
    ]);
    assert!(ok, "quota explain failed: {stderr}");
    stdout
}

fn sha256_hex(bytes: &[u8]) -> String {
    let mut hasher = Sha256::new();
    hasher.update(bytes);
    hasher
        .finalize()
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

/// AC1: every `FigureKind`/`PoolScope` appears correctly tagged, and
/// `authority` ("simulated_advisory") is present on every pacing-derived
/// value — checked on `gauge.json`, which has a host (gauge) window, a
/// principal (period) window, and one task, so all three scopes and all
/// four figure kinds are exercised in a single run.
#[test]
fn ac1_json_tags_every_figure_kind_scope_and_authority() {
    let v = run_json("gauge.json", "1970-01-01T00:00:00Z");
    let text = v.to_string();
    for kind in ["QUOTA_SNAPSHOT", "ACTUAL", "HOLD", "FORECAST"] {
        assert!(text.contains(kind), "missing figure kind {kind} in {text}");
    }
    for scope in ["\"HOST\"", "\"PRINCIPAL\"", "\"TASK\""] {
        assert!(text.contains(scope), "missing scope {scope} in {text}");
    }
    assert!(
        text.matches("simulated_advisory").count() >= 4,
        "authority must be present on multiple pacing-derived values: {text}"
    );
}

/// AC2: an idle task scenario's rendered ceiling equals the policy's own
/// `hard_ceiling`, the output contains no `%` and no bare `100` token
/// (checked as a whole token, never a substring — a timestamp or amount
/// containing "100" as part of a larger number must not false-positive),
/// and the one period window's `remaining` always renders `upper_bound`.
#[test]
fn ac2_idle_task_ceiling_matches_policy_no_percent_or_bare_100() {
    let v = run_json("idle_task.json", "1970-01-01T00:00:00Z");

    assert_eq!(v["tasks"][0]["ceiling"]["value"]["amount"], 327_000);
    assert_eq!(v["tasks"][0]["ceiling"]["value"]["kind"], "tokens");
    assert_eq!(v["tasks"][0]["ceiling"]["policy_name"], "fixture-policy");

    let window = &v["principal"][0];
    assert_eq!(window["remaining"]["state"], "upper_bound");

    let text = run_text("idle_task.json", "1970-01-01T00:00:00Z", "120");
    assert!(
        !text.contains('%'),
        "output must never show a raw percent sign: {text}"
    );
    let has_bare_100 = text
        .split(|c: char| !c.is_alphanumeric())
        .any(|tok| tok == "100");
    assert!(!has_bare_100, "output contains a bare 100 token: {text}");
}

/// AC3: a stale gauge snapshot renders `stale`; a gauge window anywhere
/// in the scenario forces the scenario-level forecast to `unknown` with
/// the specific "simulator does not consume provider snapshots" reason
/// (never "missing"); and `--width 40`/`--width 80` both fit every line
/// and contain no ANSI escape byte.
#[test]
fn ac3_stale_gauge_forecast_unknown_and_width_fixtures() {
    let fresh = run_json("gauge.json", "1970-01-01T00:00:00Z");
    assert_eq!(fresh["host"][0]["snapshot"]["state"], "exact");

    let stale = run_json("gauge.json", "1970-01-01T01:00:00Z");
    assert_eq!(stale["host"][0]["snapshot"]["state"], "stale");

    assert_eq!(fresh["next_safe_action"]["value"]["state"], "unknown");
    let reason = fresh["next_safe_action"]["value"]["reason"]
        .as_str()
        .expect("reason is a string");
    assert!(
        reason.contains("simulator does not consume provider snapshots"),
        "unexpected reason: {reason}"
    );

    for width in ["40", "80"] {
        let text = run_text("gauge.json", "1970-01-01T00:00:00Z", width);
        assert!(
            !text.contains('\u{1b}'),
            "ANSI escape byte found at width {width}: {text:?}"
        );
        let max_width: usize = width.parse().unwrap();
        for line in text.lines() {
            assert!(
                line.chars().count() <= max_width,
                "line exceeds width {width} ({} chars): {line:?}",
                line.chars().count()
            );
        }
    }
}

/// AC4, first half: `doctor`'s existing finding ids keep their relative
/// order, and `pacing_authority` is appended immediately after
/// `quota_source_mode` — never reordering or dropping an existing
/// finding.
#[test]
fn ac4_doctor_finding_order_unchanged_pacing_authority_follows_quota_source_mode() {
    let scratch = tempfile::tempdir().expect("scratch dir");
    let state_dir = scratch.path().join("state");

    let output = Command::new(bin())
        .args(["doctor", "--json"])
        .env("LIBRA_GOVERNOR_STATE_DIR", &state_dir)
        .env("HOME", scratch.path())
        .output()
        .expect("spawn doctor");
    let v: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("doctor --json output is valid JSON");
    let ids: Vec<String> = v["findings"]
        .as_array()
        .expect("findings array")
        .iter()
        .map(|f| f["id"].as_str().unwrap().to_string())
        .collect();

    let expected_relative_order = [
        "claude_settings",
        "codex_hooks",
        "quota_source_mode",
        "pacing_authority",
    ];
    let positions: Vec<usize> = expected_relative_order
        .iter()
        .map(|id| {
            ids.iter()
                .position(|x| x == id)
                .unwrap_or_else(|| panic!("missing finding id {id:?} in {ids:?}"))
        })
        .collect();
    assert!(
        positions.windows(2).all(|w| w[0] < w[1]),
        "existing finding ids must keep their relative order: {ids:?}"
    );
    let quota_source_mode_pos = ids.iter().position(|x| x == "quota_source_mode").unwrap();
    let pacing_authority_pos = ids.iter().position(|x| x == "pacing_authority").unwrap();
    assert_eq!(
        pacing_authority_pos,
        quota_source_mode_pos + 1,
        "pacing_authority must immediately follow quota_source_mode: {ids:?}"
    );

    let pacing_finding = v["findings"]
        .as_array()
        .unwrap()
        .iter()
        .find(|f| f["id"] == "pacing_authority")
        .unwrap();
    assert_eq!(pacing_finding["severity"], "ok");
}

/// AC4, second half: a `quota explain` run never touches `$HOME` or the
/// state directory — verified with an actual byte-hash comparison of an
/// existing file plus a real emptiness check, not merely "didn't crash".
#[test]
fn ac4_quota_explain_never_touches_home_or_state_dir() {
    let scratch = tempfile::tempdir().expect("scratch dir");
    let home = scratch.path().join("home");
    std::fs::create_dir_all(&home).expect("create home");
    let settings_path = home.join("settings.json");
    std::fs::write(&settings_path, b"{\"untouched\":true}\n").expect("write settings.json");
    let before_hash = sha256_hex(&std::fs::read(&settings_path).unwrap());
    let state_dir = scratch.path().join("state");

    let output = Command::new(bin())
        .args([
            "quota",
            "explain",
            "--replay",
            &fixture("idle_task.json"),
            "--as-of",
            "1970-01-01T00:00:00Z",
            "--json",
        ])
        .env("LIBRA_GOVERNOR_STATE_DIR", &state_dir)
        .env("HOME", &home)
        .output()
        .expect("spawn quota explain");
    assert!(
        output.status.success(),
        "stderr: {}",
        String::from_utf8_lossy(&output.stderr)
    );

    let after_hash = sha256_hex(&std::fs::read(&settings_path).unwrap());
    assert_eq!(
        before_hash, after_hash,
        "quota explain must never modify an unrelated file under $HOME"
    );
    assert!(
        !state_dir.exists() || std::fs::read_dir(&state_dir).unwrap().next().is_none(),
        "quota explain must never create or populate the state directory"
    );
}

/// AC5(a): a task's own `actual` reflects only that task's reported
/// spend, never another task's — even though both tasks' holds pool
/// together under any window of matching unit (see
/// `pacing::step::pending_for_window`'s own docs on why windows are not
/// principal-partitioned).
#[test]
fn ac5a_task_actual_never_leaks_another_tasks_spend() {
    let v = run_json("two_principal.json", "1970-01-01T00:01:00Z");
    let tasks = v["tasks"].as_array().expect("tasks array");
    let task1 = tasks.iter().find(|t| t["task"] == 1).expect("task 1");
    let task2 = tasks.iter().find(|t| t["task"] == 2).expect("task 2");

    assert_eq!(task1["actual"]["state"], "exact");
    assert_eq!(task1["actual"]["value"], 111);
    assert_eq!(
        task2["actual"]["state"], "unknown",
        "task 2 never reported a Spend — it must never inherit task 1's"
    );
}

/// AC5(b): a Principal-scoped window renders `unknown` once a second
/// principal's tasks also exist in the scenario — usage is not
/// principal-attributed (ADR-0016 §5).
#[test]
fn ac5b_principal_window_unknown_with_multiple_principals() {
    let v = run_json("two_principal.json", "1970-01-01T00:01:00Z");
    let principal_windows = v["principal"].as_array().expect("principal windows");
    assert_eq!(principal_windows.len(), 1);
    let w = &principal_windows[0];
    assert_eq!(w["actual"]["state"], "unknown");
    assert_eq!(w["held"]["state"], "unknown");
    assert_eq!(w["remaining"]["state"], "unknown");
    let reason = w["actual"]["reason"].as_str().expect("reason is a string");
    assert!(reason.contains("ADR-0016"), "unexpected reason: {reason}");
}

/// AC5(c): running the same input twice produces byte-identical output,
/// in both JSON and text form.
#[test]
fn ac5c_same_input_twice_is_byte_identical() {
    let (_, json_a, _) = run_raw(&[
        "quota",
        "explain",
        "--replay",
        &fixture("idle_task.json"),
        "--as-of",
        "1970-01-01T00:00:00Z",
        "--json",
    ]);
    let (_, json_b, _) = run_raw(&[
        "quota",
        "explain",
        "--replay",
        &fixture("idle_task.json"),
        "--as-of",
        "1970-01-01T00:00:00Z",
        "--json",
    ]);
    assert_eq!(json_a, json_b);

    let text_a = run_text("idle_task.json", "1970-01-01T00:00:00Z", "80");
    let text_b = run_text("idle_task.json", "1970-01-01T00:00:00Z", "80");
    assert_eq!(text_a, text_b);
}

/// Security regression: `malicious_principal.json` carries a task
/// principal (and, separately, a policy name) containing a raw ESC
/// byte opening an OSC title-spoof sequence, a CSI clear-screen
/// sequence, a BEL, and an embedded newline attempting to forge a fake
/// additional `[SIM]`-prefixed output line. None of this may reach
/// stdout raw in text mode — `render::sanitize_for_terminal` must strip
/// every control byte from the fully composed line before it is
/// written. JSON mode is checked too, confirming empirically (not just
/// assumed) that `serde_json`'s own escaping already keeps a raw
/// control byte out of that output as well.
#[test]
fn malicious_principal_is_neutralized_in_text_output_and_absent_in_json_bytes() {
    let path = fixture("malicious_principal.json");

    for width in ["40", "80", "120"] {
        let output = Command::new(bin())
            .args([
                "quota",
                "explain",
                "--replay",
                &path,
                "--as-of",
                "1970-01-01T00:00:00Z",
                "--width",
                width,
            ])
            .output()
            .expect("spawn quota explain");
        assert!(
            output.status.success(),
            "stderr: {}",
            String::from_utf8_lossy(&output.stderr)
        );

        // Check the raw bytes, not just a lossy UTF-8 string: an ESC or
        // BEL byte is itself valid single-byte UTF-8, so a lossy
        // re-encoding could never hide one even if it wanted to — this
        // is the strongest form of the check, not a weaker one.
        assert!(
            !output.stdout.contains(&0x1b),
            "ESC byte leaked into text stdout at width {width}"
        );
        assert!(
            !output.stdout.contains(&0x07),
            "BEL byte leaked into text stdout at width {width}"
        );
        assert!(
            !output.stdout.contains(&0x0d),
            "CR byte leaked into text stdout at width {width}"
        );

        let text = String::from_utf8_lossy(&output.stdout);
        assert!(
            !text.lines().any(|l| l == "[SIM] fake line"),
            "a forged [SIM]-prefixed line was injected via an embedded \
             newline at width {width}: {text:?}"
        );
        assert!(
            !text.contains("]0;pwned"),
            "an OSC title-spoof sequence's body leaked through at width {width}: {text:?}"
        );
    }

    // JSON mode: `serde_json` already escapes every control byte as a
    // textual `\u00XX` sequence, so the raw bytes on stdout must never
    // contain the literal ESC/BEL byte either — verified empirically,
    // not assumed.
    let output = Command::new(bin())
        .args([
            "quota",
            "explain",
            "--replay",
            &path,
            "--as-of",
            "1970-01-01T00:00:00Z",
            "--json",
        ])
        .output()
        .expect("spawn quota explain --json");
    assert!(output.status.success());
    assert!(
        !output.stdout.contains(&0x1b),
        "ESC byte present raw in JSON-mode stdout"
    );
    assert!(
        !output.stdout.contains(&0x07),
        "BEL byte present raw in JSON-mode stdout"
    );
    let v: serde_json::Value =
        serde_json::from_slice(&output.stdout).expect("quota explain --json output is valid JSON");
    // The value itself is still faithfully preserved (escaped, not
    // dropped) in JSON mode — this surface's job is to neutralize a
    // terminal injection, never to silently discard legitimate
    // caller-supplied text.
    let principal = v["tasks"][0]["principal"].as_str().unwrap();
    assert!(principal.contains('\u{1b}'));
}
